include('./assets/conjure.js');
include('./core/conjure.js');
include('./ecs/conjure.js');
include('./editor/conjure.js');
include('./events/conjure.js');
include('./graphics/conjure.js');
include('./logger/conjure.js');
include('./math/conjure.js');
include('./tempest/conjure.js');