require('premake', '>=5.0.0-beta3')

fetch = require 'build/fetch'
require 'build/install'
scoped = require 'build/premake-scoped'
require 'build/tests'

local function embed_web_assets()
    local root_dir = _MAIN_SCRIPT_DIR or _WORKING_DIR or '.'
    local web_dir = path.join(root_dir, 'engine/runtime/profiler/web')
    local out_file = path.join(root_dir, 'engine/runtime/profiler/src/web_assets.cpp')

    local function read_file(filepath)
        local f = io.open(filepath, 'rb')
        if not f then return '' end
        local content = f:read('*all')
        f:close()
        return content
    end

    local html_content = read_file(path.join(web_dir, 'index.html'))
    local css_content = read_file(path.join(web_dir, 'styles.css'))
    local js_content = read_file(path.join(web_dir, 'app.js'))

    local out = {}
    table.insert(out, '// Auto-generated by premake5 from engine/runtime/profiler/web/\n')
    table.insert(out, '// DO NOT EDIT DIRECTLY. Edit web/index.html, web/styles.css, web/app.js instead.\n\n')
    table.insert(out, '#include "web_assets.hpp"\n\n')
    table.insert(out, 'namespace tempest::profiler\n{\n    namespace\n    {\n')
    table.insert(out, '        constexpr const char s_index_html[] = R"raw_html(' .. html_content .. ')raw_html";\n\n')
    table.insert(out, '        constexpr const char s_styles_css[] = R"raw_css(' .. css_content .. ')raw_css";\n\n')
    table.insert(out, '        constexpr const char s_app_js[] = R"raw_js(' .. js_content .. ')raw_js";\n')
    table.insert(out, '    } // namespace\n\n')
    table.insert(out, '    auto get_embedded_index_html() noexcept -> string_view\n    {\n        return string_view{s_index_html, sizeof(s_index_html) - 1};\n    }\n\n')
    table.insert(out, '    auto get_embedded_app_js() noexcept -> string_view\n    {\n        return string_view{s_app_js, sizeof(s_app_js) - 1};\n    }\n\n')
    table.insert(out, '    auto get_embedded_styles_css() noexcept -> string_view\n    {\n        return string_view{s_styles_css, sizeof(s_styles_css) - 1};\n    }\n')
    table.insert(out, '} // namespace tempest::profiler\n')

    local function normalize_newlines(str)
        return (str:gsub('\r\n', '\n'))
    end

    local generated = normalize_newlines(table.concat(out))
    local current = normalize_newlines(read_file(out_file))
    if generated ~= current then
        local f = io.open(out_file, 'wb')
        if f then
            f:write(generated)
            f:close()
        end
    end
end

newaction {
    trigger = 'embed-web-assets',
    description = 'Generate embedded C++ web assets from web/ files',
    execute = embed_web_assets,
}

embed_web_assets()

-- Ensure workspace assets directory and vendor symlinks exist
local workspaceAssetsDir = path.join(_MAIN_SCRIPT_DIR, 'assets')
if not os.isdir(workspaceAssetsDir) then
    os.mkdir(workspaceAssetsDir)
end

local gltfLink = path.join(workspaceAssetsDir, 'glTF-Sample-Assets')
if not os.islink(gltfLink) and not os.isdir(gltfLink) then
    local gltfTarget = path.join(_MAIN_SCRIPT_DIR, 'vendor/glTF-Sample-Assets')
    if os.isdir(gltfTarget) then
        os.linkdir(gltfTarget, gltfLink)
    end
end

local polyLink = path.join(workspaceAssetsDir, 'polyhaven')
if not os.islink(polyLink) and not os.isdir(polyLink) then
    local polyTarget = path.join(_MAIN_SCRIPT_DIR, 'vendor/polyhaven')
    if os.isdir(polyTarget) then
        os.linkdir(polyTarget, polyLink)
    end
end

scoped.workspace('Tempest', function()
    configurations { 'Debug', 'Release', 'RelWithDebugInfo' }
    platforms { 'x64' }
    defaultplatform 'x64'
    location 'build/%{_ACTION}'

    if _ACTION == 'compilecommands' then
        os.mkdir('build/compilecommands')
    end

    scoped.filter({
        'action:not vs*'
    }, function()
         toolset 'clang'
    end)

    scoped.filter({
        'action:vs*'
    }, function()
        toolset 'v143'
        usestandardpreprocessor 'On'
        disablewarnings { '4251' }
    end)

    scoped.filter({
        'action:vs2026'
    }, function()
        toolset 'v145'
    end)

    scoped.filter({
        'configurations:Debug'
    }, function()
        defines { '_DEBUG' }

        scoped.filter({
            'action:vs*'
        }, function()
            symbols 'Full'
        end)

        scoped.filter({
            'action:not vs*'
        }, function()
            symbols 'On'
        end)
    end)

    scoped.filter({
        'configurations:Release'
    }, function()
        defines { 'NDEBUG' }
        optimize 'Full'
    end)

    scoped.filter({
        'configurations:RelWithDebugInfo'
    }, function()
        defines { 'NDEBUG' }
        optimize 'On'
    end)

    scoped.filter({
        'configurations:Debug or RelWithDebugInfo',
    }, function()
        defines { 'TEMPEST_ENABLE_DEBUG_MARKERS' }

        scoped.filter({
            'action:vs*',
        }, function()
            symbols 'Full'
        end)
        
        scoped.filter({
            'action:not vs*',
        }, function()
            symbols 'On'
        end)
    end)

    scoped.filter({
        'platforms:x64'
    }, function()
        architecture 'x86_64'
    end)

    scoped.filter({
        'system:windows'
    }, function()
        systemversion 'latest'
        staticruntime 'Off'
    end)

    binaries = '%{wks.basedir}/bin/%{cfg.buildcfg}/%{cfg.system}-%{cfg.toolset}'
    intermediates = '%{wks.basedir}/bin-int/%{cfg.buildcfg}/%{cfg.system}-%{cfg.toolset}'

    scoped.filter({
        'action:vs*'
    }, function()
        multiprocessorcompile 'On'
    end)

    scoped.filter({
        'action:export-compile-commands',
        'toolset:clang',
    }, function()
        buildoptions {
            '-march=native'
        }
    end)

    scoped.filter({
        'toolset:clang',
        'system:windows',
        'action:not vs*',
        'configurations:Debug',
        'kind:ConsoleApp or SharedLib or WindowedApp'
    }, function()
        linkoptions {
            '-dll_dbg',
            '-Xlinker /NODEFAULTLIB:libcmt'
        }

        links {
            "msvcrtd"
        }
    end)

    scoped.filter({
        'toolset:clang',
        'system:windows',
        'action:not vs*',
        'configurations:RelWithDebugInfo or Release',
        'kind:ConsoleApp or SharedLib or WindowedApp'
    }, function()
        linkoptions {
            '-dll',
            '-Xlinker /NODEFAULTLIB:libcmt'
        }

        links {
            "msvcrt"
        }
    end)

    scoped.filter({
        'configurations:Release'
    }, function()
        omitframepointer 'On'
    end)

    scoped.filter({
        'toolset:clang',
        'action:not vs*'
    }, function()
        disablewarnings {
            'missing-designated-field-initializers',
        }
    end)

    scoped.filter({
        'options:use-asan'
    }, function()
        sanitize { 'Address' }
        
        scoped.filter({
            'toolset:msc*',
            'configurations:Debug',
        }, function()
            editandcontinue 'Off'
        end)

        scoped.filter({
            'toolset:clang',
            'system:not windows',
        }, function()
            buildoptions {
                '-fno-omit-frame-pointer',
                '-g'
            }
        end)
    end)

    scoped.filter({
        'toolset:msc*',
        'configurations:RelWithDebugInfo',
    }, function()
        dynamicdebugging 'On'
    end)

    scoped.filter({
        'toolset:clang*',
        'system:windows',
        'action:ninja',
        'configurations:Debug',
    }, function()
        buildoptions {
            '-gcodeview'
        }

        linkoptions {
            '-Wl,/DEBUG'
        }
    end)

    scoped.filter({
        'configurations:Debug',
    }, function()
        optimize 'Debug'
    end)

    startproject 'editor-entrypoint'

    include 'dependencies'
    include 'engine'
    include 'game'
end)

newoption {
    trigger = 'use-asan',
    description = 'Use AddressSanitizer',
    category = 'Tempest Engine',
}
