name: Build Linux

on: [push]

jobs:
  cpp-build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        config: [ debug, release ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure Ubuntu Libraries
        run: sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev mesa-common-dev
      - name: Install Premake
        uses: Jarod42/install-premake5@v4
        with:
          ref: master
      - name: Generate Project
        run: premake5 gmake
      - name: Configure Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 19
          platform: x64
      - name: Build
        run: make config=${{ matrix.config }} -j$(nproc)
