name: Compile Tempest

on: [push]

jobs:
  cpp-linux-build:
    name: Build Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        config: [ debug, release ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update apt-get
        run: sudo apt-get update -y
      - name: Configure Ubuntu Libraries
        run: sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev mesa-common-dev
      - name: Install Clang 19
        uses: egor-tensin/setup-clang@v1
        with:
          version: 19
          platform: x64
      - name: Install Premake
        uses: Jarod42/install-premake5@v4
        with:
          ref: master
      - name: Generate Project Files
        run: premake5 gmake
      - name: Fetch Dependencies
        run: premake5 fetch
      - name: Build
        run: make config=${{ matrix.config }}_x64 -j$(nproc)

  cpp-windows-build:
    name: Build Windows
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-2022 ]
        config: [ debug, release ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Install Premake
        uses: Jarod42/install-premake5@v4
        with:
          ref: master
      - name: Generate Project Files
        run: premake5 vs2022
      - name: Fetch Dependencies
        run: premake5 fetch
      - name: Build
        run: |
          $config = (Get-Culture).TextInfo.ToTitleCase("${{ matrix.config }}")
          msbuild -p:Configuration=$config -p:Platform=x64 -m